// components/Donation.vue
<template>
  <span>
    <v-tooltip top>
      <template v-slot:activator="{ on, attrs }">
        <span
          v-bind="attrs"
          v-on="on"
          @click="
            copyToClipboard(coin.address);
            snackbar = true;
          "
        >
          <img :src="coin.url" class="cryptoicon" />
        </span>
        <v-snackbar v-model="snackbar" :timeout="timeout">
          <center>{{ coin.name }} {{ snackbarText }}</center>
        </v-snackbar>
      </template>
      <span>{{ coin.address }}</span>
    </v-tooltip>
  </span>
</template>

<style>
.cryptoicon {
  vertical-align: middle;
  max-height: 18px;
}
</style>

<script>
export default {
  data() {
    return {
      snackbar: false,
      snackbarText: "wallet address copied to clipboard",
      timeout: 1234
    };
  },
  props: ["coin"],
  methods: {
    copyToClipboard(address) {
      navigator.clipboard.writeText(address);
    }
  }
};
</script>

// components/Donation.tsx
"use client";

import { useState } from "react";

interface Coin {
  name: string;
  url: string;
  address: string;
}

export function Donation({ coin }: { coin: Coin }) {
  const [copied, setCopied] = useState(false);

  const handleClick = async () => {
    await navigator.clipboard.writeText(coin.address);
    setCopied(true);
    setTimeout(() => setCopied(false), 1234);
  };

  return (
    <span className="relative group">
      <button onClick={handleClick} title={coin.address} className="align-middle mx-1">
        <img src={coin.url} alt={coin.name} className="h-4 inline" />
      </button>
      {copied && (
        <span className="absolute bottom-6 left-1/2 -translate-x-1/2 bg-neutral-800 text-xs px-2 py-1 rounded whitespace-nowrap z-10">
          {coin.name} wallet address copied to clipboard
        </span>
      )}
    </span>
  );
}
