// pages/wassies.vue
<template>
  <v-row justify="center" align="center">
    <v-col cols="12" sm="8" md="6">
      <v-card class="mx-auto" max-width="500">
        <v-card-title class="headline">
          All Wassies Are Rare Calculator
        </v-card-title>
        <v-card-subtitle>disclaimer: issa joke</v-card-subtitle>
        <Search />
      </v-card>
    </v-col>
  </v-row>
</template>

// app/wassies/page.tsx
import { WassieSearch } from "@/components/WassieSearch";

export default function Wassies() {
  return (
    <div className="flex justify-center">
      <div className="w-full max-w-sm">
        <div className="bg-neutral-900 border border-neutral-800 rounded-lg p-6">
          <h1 className="text-xl font-bold mb-1">All Wassies Are Rare Calculator</h1>
          <p className="text-neutral-500 text-sm mb-4">disclaimer: issa joke</p>
          <WassieSearch />
        </div>
      </div>
    </div>
  );
}
